export interface RealmCatalogEntry {
  realm_name: string;
  region: string;
}

const AMERICAS_REALM_NAMES = [
  "Aerie Peak",
  "Agamaggan",
  "Aggramar",
  "Akama",
  "Alexstrasza",
  "Alleria",
  "Altar of Storms",
  "Alterac Mountains",
  "Andorhal",
  "Anetheron",
  "Antonidas",
  "Anub'arak",
  "Anvilmar",
  "Arathor",
  "Archimonde",
  "Area 52",
  "Argent Dawn",
  "Arthas",
  "Arygos",
  "Auchindoun",
  "Azgalor",
  "Azjol-Nerub",
  "Azralon",
  "Azshara",
  "Azuremyst",
  "Baelgun",
  "Balnazzar",
  "Barthilas",
  "Black Dragonflight",
  "Blackhand",
  "Blackrock",
  "Blackwater Raiders",
  "Blackwing Lair",
  "Blade's Edge",
  "Bladefist",
  "Bleeding Hollow",
  "Blood Furnace",
  "Bloodhoof",
  "Bloodscalp",
  "Bonechewer",
  "Boulderfist",
  "Bronzebeard",
  "Burning Blade",
  "Burning Legion",
  "Caelestrasz",
  "Cairne",
  "Cenarion Circle",
  "Cenarius",
  "Cho'gall",
  "Chromaggus",
  "Coilfang",
  "Crushridge",
  "Daggerspine",
  "Dalaran",
  "Dalvengyr",
  "Darkspear",
  "Dath'Remar",
  "Dawnbringer",
  "Deathwing",
  "Demon Soul",
  "Dentarg",
  "Destromath",
  "Dethecus",
  "Detheroc",
  "Doomhammer",
  "Draenor",
  "Draka",
  "Drakkari",
  "Drak'tharon",
  "Dreadmaul",
  "Drenden",
  "Durotan",
  "Duskwood",
  "Earthen Ring",
  "Echo Isles",
  "Eitrigg",
  "Eldre'Thalas",
  "Elune",
  "Emerald Dream",
  "Eonar",
  "Eredar",
  "Executus",
  "Exodar",
  "Farstriders",
  "Feathermoon",
  "Fenris",
  "Firetree",
  "Frostmane",
  "Frostmourne",
  "Frostwolf",
  "Galakrond",
  "Garithos",
  "Garona",
  "Garrosh",
  "Ghostlands",
  "Gilneas",
  "Gnomeregan",
  "Goldrinn",
  "Gorefiend",
  "Gorgonnash",
  "Greymane",
  "Grizzly Hills",
  "Gundrak",
  "Gurubashi",
  "Hakkar",
  "Haomarush",
  "Hellscream",
  "Hydraxis",
  "Hyjal",
  "Icecrown",
  "Illidan",
  "Jaedenar",
  "Jubei'Thos",
  "Kael'thas",
  "Kalecgos",
  "Kargath",
  "Kel'Thuzad",
  "Khadgar",
  "Khaz Modan",
  "Kil'jaeden",
  "Kilrogg",
  "Kirin Tor",
  "Korialstrasz",
  "Kul Tiras",
  "Laughing Skull",
  "Lethon",
  "Lightbringer",
  "Lightning's Blade",
  "Lightninghoof",
  "Llane",
  "Lothar",
  "Magtheridon",
  "Maiev",
  "Mal'Ganis",
  "Malfurion",
  "Malygos",
  "Mannoroth",
  "Medivh",
  "Misha",
  "Mok'Nathal",
  "Moon Guard",
  "Moonrunner",
  "Mug'thol",
  "Muradin",
  "Nagrand",
  "Nathrezim",
  "Nazgrel",
  "Nesingwary",
  "Nordrassil",
  "Norgannon",
  "Onyxia",
  "Perenolde",
  "Proudmoore",
  "Quel'Thalas",
  "Ragnaros",
  "Ravencrest",
  "Rexxar",
  "Rivendare",
  "Runetotem",
  "Sargeras",
  "Saurfang",
  "Scilla",
  "Sen'jin",
  "Sentinels",
  "Shadow Council",
  "Shadowmoon",
  "Shadowsong",
  "Shandris",
  "Shattered Halls",
  "Shu'halo",
  "Silver Hand",
  "Sisters of Elune",
  "Skullcrusher",
  "Skywall",
  "Smolderthorn",
  "Spinebreaker",
  "Spirestone",
  "Staghelm",
  "Steamwheedle Cartel",
  "Stonemaul",
  "Stormrage",
  "Stormreaver",
  "Stormscale",
  "Suramar",
  "Tanaris",
  "Terenas",
  "Terokkar",
  "Thaurissan",
  "The Forgotten Coast",
  "The Scryers",
  "The Venture Co",
  "Thorium Brotherhood",
  "Thrall",
  "Thunderhorn",
  "Thunderlord",
  "Tichondrius",
  "Tol Barad",
  "Turalyon",
  "Twisting Nether",
  "Uldaman",
  "Uldum",
  "Undermine",
  "Uther",
  "Vashj",
  "Vek'nilash",
  "Velen",
  "Warsong",
  "Whisperwind",
  "Wildhammer",
  "Windrunner",
  "Winterhoof",
  "Wyrmrest Accord",
  "Ysera",
  "Ysondre",
  "Zul'jin",
  "Zuluhed",
];

export const REALM_CATALOG: RealmCatalogEntry[] = AMERICAS_REALM_NAMES.map((realm_name) => ({
  realm_name,
  region: "us",
}));

const REALM_CATALOG_MAP = new Map(REALM_CATALOG.map((realm) => [realm.realm_name, realm]));

export function getRealmCatalogEntry(realmName: string) {
  return REALM_CATALOG_MAP.get(realmName) ?? null;
}
